### ISSUE TITLE
Consider merging with cordova-plugin-android-window-background

### ISSUE THREAD

**Issue by marcusforsberg** [douglaszaltron/cordova-plugin-window-background#2]
Hi there,

I noticed that you've updated this plugin with some more features since I released my own variant last year.

I'd like to invite you to submit a pull request to our repo at https://github.com/winteragency/cordova-plugin-android-window-background so that we can have a single plugin and repo for this.

It makes no sense for us to maintain two seperate plugins doing the same thing, and seeing as you've copied the entire readme-file from our repo, it will only serve as a confusion for people trying to find the right plugin to use.

Please go ahead and open a pull request with your new changes for the theme color features as well as adding your name to the readme and we'll gladly merge it.

**Comment by douglaszaltron** [comment]
Hi @marcusforsberg, thanks for your suggestions! That is truth.

About the theme color features, I think that goes against the whole idea of making small plugins that do one thing well and you can throw together into a project as you need them. I did it because I needed something fast but I believe it is not ideal for your current plugin!
